defaults: &defaults
  docker:
    - image: circleci/node:16
  working_directory: /home/circleci/spr

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - save_cache:
          paths:
            - ~/spr
          key: v1-repo-{{ .Revision }}
  release:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}
      - run:
          name: release
          command: npx semantic-release || true
  pre-release:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}
      - run:
          name: pre-release
          command: unset CIRCLE_PR_NUMBER; unset CIRCLE_PULL_REQUEST; unset CI_PULL_REQUEST; ./cli.js
      - save_cache:
          paths:
            - ~/spr/package.json
          key: v1-pkg-{{ .Revision }}
  notify-pr:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}
      - restore_cache:
          keys:
            - v1-pkg-{{ .Revision }}
      - run:
          name: notify pr
          command: 'npx decorate-gh-pr -f scripts/notifyPr.js'

workflows:
  version: 2
  test-and-publish:
    jobs:
      - install
      - release:
          requires:
            - install
          filters:
            branches:
              only: master
      - pre-release:
          requires:
            - install
          filters:
            branches:
              ignore: master
      - notify-pr:
          requires:
            - pre-release
          filters:
            branches:
              ignore:
                - master
