defaults: &defaults
  docker:
    - image: circleci/node:12
  working_directory: /home/circleci/spr

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - save_cache:
          paths:
            - ~/spr
          key: v1-repo-{{ .Revision }}
  release:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}
      - run:
          name: release
          command: npx semantic-release || true
  pre-release:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}
      - run:
          name: pre-release
          command: unset CIRCLE_PR_NUMBER; unset CIRCLE_PULL_REQUEST; unset CI_PULL_REQUEST; npx semantic-release || true

workflows:
  version: 2
  test-and-publish:
    jobs:
      - install
      - release:
          requires:
            - install
          filters:
            branches:
              only: master
      - pre-release:
          requires:
            - install
          filters:
            branches:
              ignore: master
